networks:
  nakivojp-network:
    driver: bridge
volumes:
  postgresql-volume:
  redis-volume:
  rabbitmq-volume:

services:
  postgresql:
    container_name: nakivojp-postgresql
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    ports:
      - ${POSTGRESQL_PORT}:5432
    volumes:
      - postgresql-volume:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_MULTIPLE_DATABASES: ${POSTGRESQL_DB}
    networks:
      - nakivojp-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRESQL_USER} -d postgres" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  redis:
    container_name: nakivojp-redis
    image: redis:8.8.1-trixie
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - nakivojp-network
    volumes:
      - redis-volume:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 50

  rabbitmq:
    container_name: nakivojp-rabbitmq
    hostname: rabbitmq
    image: docker.io/rabbitmq:4.3.4-management-alpine
    ports:
      - ${RABBITMQ_PORT}:5672
      - ${RABBITMQ_MANAGEMENT_PORT}:15672
    volumes:
      - rabbitmq-volume:/var/lib/rabbitmq
    networks:
      - nakivojp-network
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  jewish-slave-owner:
    container_name: nakivojp-jewish-slave-owner
    build:
      context: ..
      dockerfile: nakivojp-slave-owner/Dockerfile
    ports:
      - ${SLAVE_OWNER_PORT}:9090
    environment:
      SPRING_PROFILES_ACTIVE: dev
      POSTGRESQL_DB: ${POSTGRESQL_DB}
      POSTGRESQL_USER: ${POSTGRESQL_USER}
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRESQL_HOST: postgresql
      POSTGRESQL_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    networks:
      - nakivojp-network
    depends_on:
      postgresql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/api/actuator/health" ]
      interval: 5s
      timeout: 30s
      retries: 3
      start_period: 40s

  black-slave:
    container_name: nakivojp-black-slave
    build:
      context: ..
      dockerfile: nakivojp-slave/Dockerfile
    ports:
      - ${BLACK_SLAVE_PORT}:9091
    environment:
      SPRING_PROFILES_ACTIVE: dev
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    networks:
      - nakivojp-network
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9091/actuator/health" ]
      interval: 5s
      timeout: 30s
      retries: 3
      start_period: 40s

  latino-slave:
    container_name: nakivojp-latino-slave
    build:
      context: ..
      dockerfile: nakivojp-slave/Dockerfile
    ports:
      - ${LATINO_SLAVE_PORT}:9091
    environment:
      SPRING_PROFILES_ACTIVE: dev
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    networks:
      - nakivojp-network
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9091/actuator/health" ]
      interval: 5s
      timeout: 30s
      retries: 3
      start_period: 40s

  indian-slave:
    container_name: nakivojp-indian-slave
    build:
      context: ..
      dockerfile: nakivojp-slave/Dockerfile
    ports:
      - ${INDIAN_SLAVE_PORT}:9091
    environment:
      SPRING_PROFILES_ACTIVE: dev
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    networks:
      - nakivojp-network
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9091/actuator/health" ]
      interval: 5s
      timeout: 30s
      retries: 3
      start_period: 40s
