app:
  rds:
    username: ${POSTGRESQL_USER}
    password: ${POSTGRESQL_PASSWORD}
    database: ${POSTGRESQL_DB}
    host: ${POSTGRESQL_HOST}
    port: ${POSTGRESQL_PORT}
  cache:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
  job-queue:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
